=== vjekoslavradosevic/Movies-Dataset/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://or.fer.unizg.hr/orfilmovi.json",
    "type": "array",
    "title": "Movies dataset",
    "description": "A collection of movie-related data.",
    "items": {
        "type": "object",
        "title": "movie",
        "description": "information about a single movie.",
        "required": [
            "title",
            "release_date",
            "director",
            "producer",
            "duration",
            "actors",
            "genres",
            "plot",
            "reviews",
            "oscars",
            "box_office"
        ],
        "properties": {
            "title": {
                "type": "string",
                "title": "title",
                "description": "name of the movie."
            }, 
            "release_date": {
                "type": "string",
                "format": "date",
                "title": "release_date",
                "description": "release date of the movie."
            },
            "director": {
                "type": "object",
                "title": "director",
                "description": "director of the movie.",
                "required": [
                    "firstname",
                    "lastname"
                ],
                "properties": {
                    "firstname": {
                        "type": "string",
                        "title": "firstname",
                        "description": "director's firstname."
                    },
                    "lastname":{
                        "type": "string",
                        "title": "lastname",
                        "description": "director's lastname."
                    }
                }
            },
            "producer": {
                "type": "object",
                "title": "producer",
                "description": "producer of the movie.",
                "required": [
                    "firstname",
                    "lastname"
                ],
                "properties": {
                    "firstname": {
                        "type": "string",
                        "title": "firstname",
                        "description": "producer's firstname."
                    },
                    "lastname":{
                        "type": "string",
                        "title": "lastname",
                        "description": "producer's lastname."
                    }
                }
            },
            "duration": {
                "type": "number",
                "title": "duration",
                "description": "duration of the movie in minutes."
            },
            "actors": {
                "type": "array",
                "title": "actors",
                "description": "An array of movie actors.",
                "items": {
                    "type": "object",
                    "title": "actor",
                    "description": "actor cast in the movie.",
                    "required": [
                        "firstname",
                        "lastname"
                    ],
                    "properties": {
                        "firstname": {
                            "type": "string",
                            "title": "firstname",
                            "description": "actor's firstname."
                        },
                        "lastname":{
                            "type": "string",
                            "title": "lastname",
                            "description": "actor's lastname."
                        }
                    }
                }
            },
            "genres": {
                "type": "array",
                "title": "genres",
                "description": "genres present in the movie.",
                "items": {
                    "type": "string",
                    "title": "genre",
                    "description": "genre present in the movie."
                }
            },
            "plot": {
                "type": "string",
                "title": "plot",
                "description": "summary of the movie."
            }, 
            "reviews": {
                "type": "array",
                "title": "reviews",
                "description": "An array of movie reviews by popular review platforms.",
                "items": {
                    "type": "object",
                    "title": "review",
                    "description": "review of the movie.",
                    "required": [
                        "name",
                        "score"
                    ],
                    "properties": {
                        "name": {
                            "type": "string",
                            "title": "name",
                            "description": "name of the review platform."
                        },
                        "score":{
                            "type": "number",
                            "title": "score",
                            "description": "score given by the review platform."
                        }
                    }
                }
            },
            "oscars": {
                "type": "number",
                "title": "oscars",
                "description": "number of academy awards the movie won."
            }, 
            "box_office": {
                "type": "number",
                "title": "box_office",
                "description": "The total revenue generated by the movie at the box office, in millions of US dollars (USD)."
            }
        }
    }
}

=== vjekoslavradosevic/Movies-Dataset/movies.json
[{"title":"Inglourious Basterds","release_date":"2009-09-03","director":{"firstname":"Quentin","lastname":"Tarantino"},"producer":{"firstname":"Lawrence","lastname":"Bender"},"duration":153,"actors":[{"firstname":"Brad","lastname":"Pitt"},{"firstname":"Christoph","lastname":"Waltz"},{"firstname":"Diane","lastname":"Kruger"},{"firstname":"Quentin","lastname":"Tarantino"}],"genres":["Adventure","Drama","War"],"plot":"In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.","reviews":[{"name":"Metacritic","score":69},{"name":"Rotten Tomatoes","score":89},{"name":"IMDb","score":8.4}],"oscars":1,"box_office":321.5},{"title":"The Prestige","release_date":"2006-10-20","director":{"firstname":"Christopher","lastname":"Nolan"},"producer":{"firstname":"Emma","lastname":"Thomas"},"duration":130,"actors":[{"firstname":"Hugh","lastname":"Jackman"},{"firstname":"Christian","lastname":"Bale"},{"firstname":"Michael","lastname":"Caine"},{"firstname":"Scarlett","lastname":"Johansson"}],"genres":["Drama","Mystery","Sci-Fi"],"plot":"In London, two magicians engage in a competitive rivalry with tragic consequences.","reviews":[{"name":"Metacritic","score":66},{"name":"Rotten Tomatoes","score":76},{"name":"IMDb","score":8.5}],"oscars":0,"box_office":109.7},{"title":"The Revenant","release_date":"2015-12-25","director":{"firstname":"Alejandro","lastname":"Iñárritu"},"producer":{"firstname":"Alejandro","lastname":"Iñárritu"},"duration":156,"actors":[{"firstname":"Leonardo","lastname":"DiCaprio"},{"firstname":"Tom","lastname":"Hardy"},{"firstname":"Domhnall","lastname":"Gleeson"},{"firstname":"Will","lastname":"Poulter"}],"genres":["Adventure","Drama","Thriller"],"plot":"In the 1820s, a frontiersman on a fur trading expedition in the uncharted American wilderness is severely injured and left for dead. He survives and embarks on a quest for revenge against those who betrayed him.","reviews":[{"name":"Metacritic","score":76},{"name":"Rotten Tomatoes","score":78},{"name":"IMDb","score":8}],"oscars":3,"box_office":533},{"title":"Tenet","release_date":"2020-08-26","director":{"firstname":"Christopher","lastname":"Nolan"},"producer":{"firstname":"Emma","lastname":"Thomas"},"duration":150,"actors":[{"firstname":"John","lastname":"Washington"},{"firstname":"Robert","lastname":"Pattinson"},{"firstname":"Elizabeth","lastname":"Debicki"},{"firstname":"Kenneth","lastname":"Branagh"}],"genres":["Action","Sci-Fi","Thriller"],"plot":"Armed with only one word, Tenet, and fighting for the survival of the world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.","reviews":[{"name":"Metacritic","score":69},{"name":"Rotten Tomatoes","score":70},{"name":"IMDb","score":7.4}],"oscars":2,"box_office":363.1},{"title":"The Imitation Game","release_date":"2014-11-28","director":{"firstname":"Morten","lastname":"Tyldum"},"producer":{"firstname":"Nora","lastname":"Grossman"},"duration":113,"actors":[{"firstname":"Benedict","lastname":"Cumberbatch"},{"firstname":"Keira","lastname":"Knightley"},{"firstname":"Matthew","lastname":"Goode"},{"firstname":"Rory","lastname":"Kinnear"}],"genres":["Biography","Drama","Thriller"],"plot":"During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians while dealing with his own personal challenges.","reviews":[{"name":"Metacritic","score":73},{"name":"Rotten Tomatoes","score":92},{"name":"IMDb","score":8}],"oscars":1,"box_office":233.6},{"title":"Ford v Ferrari","release_date":"2019-11-15","director":{"firstname":"James","lastname":"Mangold"},"producer":{"firstname":"Peter","lastname":"Chernin"},"duration":152,"actors":[{"firstname":"Matt","lastname":"Damon"},{"firstname":"Christian","lastname":"Bale"},{"firstname":"Jon","lastname":"Bernthal"},{"firstname":"Caitriona","lastname":"Balfe"}],"genres":["Action","Biography","Drama"],"plot":"American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford and challenge Ferrari at the 24 Hours of Le Mans in 1966.","reviews":[{"name":"Metacritic","score":81},{"name":"Rotten Tomatoes","score":92},{"name":"IMDb","score":8.1}],"oscars":2,"box_office":225.5},{"title":"Pulp Fiction","release_date":"1994-10-14","director":{"firstname":"Quentin","lastname":"Tarantino"},"producer":{"firstname":"Lawrence","lastname":"Bender"},"duration":154,"actors":[{"firstname":"John","lastname":"Travolta"},{"firstname":"Samuel L.","lastname":"Jackson"},{"firstname":"Uma","lastname":"Thurman"},{"firstname":"Bruce","lastname":"Willis"}],"genres":["Crime","Drama"],"plot":"The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.","reviews":[{"name":"Metacritic","score":94},{"name":"Rotten Tomatoes","score":92},{"name":"IMDb","score":8.9}],"oscars":1,"box_office":213.9},{"title":"American Psycho","release_date":"2000-04-14","director":{"firstname":"Mary","lastname":"Harron"},"producer":{"firstname":"Chris","lastname":"Hanley"},"duration":102,"actors":[{"firstname":"Christian","lastname":"Bale"},{"firstname":"Willem","lastname":"Dafoe"},{"firstname":"Jared","lastname":"Leto"},{"firstname":"Reese","lastname":"Witherspoon"}],"genres":["Crime","Drama","Horror"],"plot":"A wealthy New York investment banker hides his alternate psychopathic ego from his circle of friends, as he delves deeper into his violent, hedonistic fantasies.","reviews":[{"name":"Metacritic","score":64},{"name":"Rotten Tomatoes","score":68},{"name":"IMDb","score":7.6}],"oscars":0,"box_office":34.3},{"title":"Fury","release_date":"2014-10-17","director":{"firstname":"David","lastname":"Ayer"},"producer":{"firstname":"Bill","lastname":"Block"},"duration":134,"actors":[{"firstname":"Brad","lastname":"Pitt"},{"firstname":"Shia","lastname":"LaBeouf"},{"firstname":"Logan","lastname":"Lerman"},{"firstname":"Michael","lastname":"Peña"}],"genres":["Action","Drama","War"],"plot":"In April 1945, a sergeant named Wardaddy commands a Sherman tank and its five-man crew on a deadly mission behind enemy lines. Outnumbered and outgunned, they face overwhelming odds in their attempt to strike at the heart of Nazi Germany.","reviews":[{"name":"Metacritic","score":64},{"name":"Rotten Tomatoes","score":76},{"name":"IMDb","score":7.6}],"oscars":0,"box_office":211.8},{"title":"The Lighthouse","release_date":"2019-10-18","director":{"firstname":"Robert","lastname":"Eggers"},"producer":{"firstname":"Robert","lastname":"Eggers"},"duration":109,"actors":[{"firstname":"Robert","lastname":"Pattinson"},{"firstname":"Willem","lastname":"Dafoe"}],"genres":["Drama","Fantasy","Horror"],"plot":"Two lighthouse keepers try to maintain their sanity while living on a remote and mysterious New England island in the 1890s.","reviews":[{"name":"Metacritic","score":83},{"name":"Rotten Tomatoes","score":90},{"name":"IMDb","score":7.6}],"oscars":0,"box_office":18.5}]
